amount_dol = input("Dollars cost: ")
amount_cent = input("and cents: ")
amount = float(amount_dol + "." + amount_cent)
quantity = int(input("Count of purchases: "))
amount_total = round(amount * quantity, 3)
print("Total is ", amount_total, "$")
